# Handle Errors in Asynchronous Functions

This lesson shows how regular control flow statements such as `try`/`catch` blocks can be used to properly handle errors in asynchronous functions. Oftentimes, the resulting code is easier to read than complex promise chains with `.catch()` methods.
